storybook: fix missing .svg TypeScript module
Use the same approach as ui-charts/src/spaceTimeChart/config.ts. Fixes
the following TypeScript error:

    stories/ui-charts/spaceTimeChart/work-schedules.stories.tsx:14:20 - error TS2307: Cannot find module './assets/images/ScheduledMaintenanceUp.svg' or its corresponding type declarations.

    14 import upward from './assets/images/ScheduledMaintenanceUp.svg';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Simon Ser <contact@emersion.fr>