front: wait for simulation button to have href attribute
react-pdf will create an anchor element without an href attribute
because instance.url is null while the PDF is being generated:
https://github.com/diegomura/react-pdf/blob/f89f75c1f132ba19b54847c3ac23efec675f8d0a/packages/renderer/src/dom/PDFDownloadLink.js#L35

This results in a fetch(null) call, downloading the current HTML
page. Later, we try to parse the PDF file and fail with:

    InvalidPDFException: Invalid PDF structure.

Signed-off-by: Simon Ser <contact@emersion.fr>