docker: fix restart policy type for core
In YAML, "no" is a boolean. This makes podman-compose choke on the
docker-compose.yml, because it expects a string:

    Error: running container create option: "False" is not a valid restart policy: invalid argument

Use a string instead, just like wait-healthy already does.