editoast: rename user info arg from "user" to "identity"
so that the help message makes it clear what the argument expects (i.e.
not a name):

    error: the following required arguments were not provided:
      <ID_OR_IDENTITY>

    Usage: editoast user info <ID_OR_IDENTITY>

    For more information, try '--help'.

Signed-off-by: Hubert Hirtz <hubert@hirtz.pm>