docker: port is an integer
Since `docker-compose.host.yml` is used to override values of
`docker-compose.yml`, and `EDITOAST_PORT` is defined as an integer
in the latter, tools like `podman` will refuse to merge the 2 files
since the value of `EDITOAST_PORT` is a different type.

```
ValueError: can't merge value of EDITOAST_PORT of type <class 'int'> and <class 'str'>
```