front: add missing dotenv dependency
Without dotenv the build fails. We were installing dotenv by chance
via storybook, but we'll drop that one in the next commit.

    #50 2.679 $ vite build
    #50 2.864 failed to load config from /app/vite.config.mts
    #50 2.864 error during build:
    #50 2.864 Error: Cannot find module 'dotenv'
    #50 2.864 Require stack:
    #50 2.864 - /app/node_modules/@import-meta-env/unplugin/dist/index.js
    #50 2.864     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    #50 2.864     at Module._load (node:internal/modules/cjs/loader:1051:27)
    #50 2.864     at Module.require (node:internal/modules/cjs/loader:1311:19)
    #50 2.864     at require (node:internal/modules/helpers:179:18)
    #50 2.864     at Object.<anonymous> (/app/node_modules/@import-meta-env/unplugin/dist/index.js:107:22)
    #50 2.864     at Module._compile (node:internal/modules/cjs/loader:1469:14)
    #50 2.864     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    #50 2.864     at Module.load (node:internal/modules/cjs/loader:1288:32)
    #50 2.864     at Module._load (node:internal/modules/cjs/loader:1104:12)
    #50 2.864     at cjsLoader (node:internal/modules/esm/translators:346:17)

Signed-off-by: Simon Ser <contact@emersion.fr>