front: disable vite-plugin-checker when running tests
vite-plugin-checker runs ESLint and TypeScript, then installs a
filesystem watcher. However the watcher trips over when running tests
with coverage reports due to a race condition.

    node:internal/event_target:1101
      process.nextTick(() => { throw err; });
                               ^
    Error: ENOENT: no such file or directory, stat '/app/tests/unit/coverage/.tmp'
        at statSync (node:fs:1737:25)
        at file:///app/node_modules/vite-plugin-checker/dist/glob.js:25:68
        at matchPatterns (file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/index.js:63:13)
        at FSWatcher._userIgnored (file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/index.js:78:20)
        at FSWatcher._isIgnored (file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/index.js:644:21)
        at FSWatcher._remove (file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/index.js:733:33)
        at file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/handler.js:508:30
        at Array.forEach (<anonymous>)
        at ReaddirpStream.<anonymous> (file:///app/node_modules/vite-plugin-checker/node_modules/chokidar/esm/handler.js:507:22)
        at Object.onceWrapper (node:events:621:28) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'stat',
      path: '/app/tests/unit/coverage/.tmp'
    }

Signed-off-by: Simon Ser <contact@emersion.fr>